//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace SPSD.Editor.Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Solution {
        
        private SiteCollection[] siteCollectionField;
        
        private WebApplication[] webApplicationField;
        
        private string nameField;
        
        private bool forceField;
        
        private bool forceFieldSpecified;
        
        private bool overwriteField;
        
        private bool overwriteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SiteCollection")]
        public SiteCollection[] SiteCollection {
            get {
                return this.siteCollectionField;
            }
            set {
                this.siteCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WebApplication")]
        public WebApplication[] WebApplication {
            get {
                return this.webApplicationField;
            }
            set {
                this.webApplicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Force {
            get {
                return this.forceField;
            }
            set {
                this.forceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForceSpecified {
            get {
                return this.forceFieldSpecified;
            }
            set {
                this.forceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OverwriteSpecified {
            get {
                return this.overwriteFieldSpecified;
            }
            set {
                this.overwriteFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SiteCollection {
        
        private SiteCollectionSites[] sitesField;
        
        private string urlField;
        
        private string ownerField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string searchUrlField;
        
        private string customTemplateField;
        
        private string templateField;
        
        private int lCIDField;
        
        private bool lCIDFieldSpecified;
        
        private string localeField;
        
        private bool time24Field;
        
        private bool time24FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sites", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiteCollectionSites[] Sites {
            get {
                return this.sitesField;
            }
            set {
                this.sitesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SearchUrl {
            get {
                return this.searchUrlField;
            }
            set {
                this.searchUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CustomTemplate {
            get {
                return this.customTemplateField;
            }
            set {
                this.customTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LCID {
            get {
                return this.lCIDField;
            }
            set {
                this.lCIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LCIDSpecified {
            get {
                return this.lCIDFieldSpecified;
            }
            set {
                this.lCIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Time24 {
            get {
                return this.time24Field;
            }
            set {
                this.time24Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Time24Specified {
            get {
                return this.time24FieldSpecified;
            }
            set {
                this.time24FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SiteCollectionSites {
        
        private SiteCollectionSitesSite[] siteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Site", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiteCollectionSitesSite[] Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SiteCollectionSitesSite {
        
        private string relativeSiteUrlField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string templateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relativeSiteUrl {
            get {
                return this.relativeSiteUrlField;
            }
            set {
                this.relativeSiteUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class WebApplication {
        
        private WebApplicationDatabase[] databaseField;
        
        private WebApplicationManagedPaths[] managedPathsField;
        
        private WebApplicationSiteCollections[] siteCollectionsField;
        
        private string urlField;
        
        private bool allowDeletionField;
        
        private bool allowDeletionFieldSpecified;
        
        private bool recreateIfExistsField;
        
        private bool recreateIfExistsFieldSpecified;
        
        private bool createOnlyIfExistsField;
        
        private bool createOnlyIfExistsFieldSpecified;
        
        private bool addURLsToHOSTSField;
        
        private bool addURLsToHOSTSFieldSpecified;
        
        private string typeField;
        
        private string nameField;
        
        private string applicationPoolField;
        
        private string applicationPoolAccountField;
        
        private int portField;
        
        private bool portFieldSpecified;
        
        private bool addURLToLocalIntranetZoneField;
        
        private bool addURLToLocalIntranetZoneFieldSpecified;
        
        private string databaseNameField;
        
        private bool useClaimsField;
        
        private bool useClaimsFieldSpecified;
        
        private bool useBasicAuthenticationField;
        
        private bool useBasicAuthenticationFieldSpecified;
        
        private bool useOnlineWebPartCatalogField;
        
        private bool useOnlineWebPartCatalogFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Database", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApplicationDatabase[] Database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManagedPaths", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApplicationManagedPaths[] ManagedPaths {
            get {
                return this.managedPathsField;
            }
            set {
                this.managedPathsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SiteCollections", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApplicationSiteCollections[] SiteCollections {
            get {
                return this.siteCollectionsField;
            }
            set {
                this.siteCollectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllowDeletion {
            get {
                return this.allowDeletionField;
            }
            set {
                this.allowDeletionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowDeletionSpecified {
            get {
                return this.allowDeletionFieldSpecified;
            }
            set {
                this.allowDeletionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool RecreateIfExists {
            get {
                return this.recreateIfExistsField;
            }
            set {
                this.recreateIfExistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecreateIfExistsSpecified {
            get {
                return this.recreateIfExistsFieldSpecified;
            }
            set {
                this.recreateIfExistsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CreateOnlyIfExists {
            get {
                return this.createOnlyIfExistsField;
            }
            set {
                this.createOnlyIfExistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateOnlyIfExistsSpecified {
            get {
                return this.createOnlyIfExistsFieldSpecified;
            }
            set {
                this.createOnlyIfExistsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AddURLsToHOSTS {
            get {
                return this.addURLsToHOSTSField;
            }
            set {
                this.addURLsToHOSTSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddURLsToHOSTSSpecified {
            get {
                return this.addURLsToHOSTSFieldSpecified;
            }
            set {
                this.addURLsToHOSTSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApplicationPool {
            get {
                return this.applicationPoolField;
            }
            set {
                this.applicationPoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApplicationPoolAccount {
            get {
                return this.applicationPoolAccountField;
            }
            set {
                this.applicationPoolAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PortSpecified {
            get {
                return this.portFieldSpecified;
            }
            set {
                this.portFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AddURLToLocalIntranetZone {
            get {
                return this.addURLToLocalIntranetZoneField;
            }
            set {
                this.addURLToLocalIntranetZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddURLToLocalIntranetZoneSpecified {
            get {
                return this.addURLToLocalIntranetZoneFieldSpecified;
            }
            set {
                this.addURLToLocalIntranetZoneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string databaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool UseClaims {
            get {
                return this.useClaimsField;
            }
            set {
                this.useClaimsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseClaimsSpecified {
            get {
                return this.useClaimsFieldSpecified;
            }
            set {
                this.useClaimsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool UseBasicAuthentication {
            get {
                return this.useBasicAuthenticationField;
            }
            set {
                this.useBasicAuthenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseBasicAuthenticationSpecified {
            get {
                return this.useBasicAuthenticationFieldSpecified;
            }
            set {
                this.useBasicAuthenticationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool UseOnlineWebPartCatalog {
            get {
                return this.useOnlineWebPartCatalogField;
            }
            set {
                this.useOnlineWebPartCatalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseOnlineWebPartCatalogSpecified {
            get {
                return this.useOnlineWebPartCatalogFieldSpecified;
            }
            set {
                this.useOnlineWebPartCatalogFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WebApplicationDatabase {
        
        private string dBServerField;
        
        private WebApplicationDatabaseDBAlias[] dBAliasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DBServer {
            get {
                return this.dBServerField;
            }
            set {
                this.dBServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DBAlias", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApplicationDatabaseDBAlias[] DBAlias {
            get {
                return this.dBAliasField;
            }
            set {
                this.dBAliasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WebApplicationDatabaseDBAlias {
        
        private bool createField;
        
        private bool createFieldSpecified;
        
        private string dBInstanceField;
        
        private int dBPortField;
        
        private bool dBPortFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Create {
            get {
                return this.createField;
            }
            set {
                this.createField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateSpecified {
            get {
                return this.createFieldSpecified;
            }
            set {
                this.createFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DBInstance {
            get {
                return this.dBInstanceField;
            }
            set {
                this.dBInstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DBPort {
            get {
                return this.dBPortField;
            }
            set {
                this.dBPortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DBPortSpecified {
            get {
                return this.dBPortFieldSpecified;
            }
            set {
                this.dBPortFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WebApplicationManagedPaths {
        
        private WebApplicationManagedPathsManagedPath[] managedPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManagedPath", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApplicationManagedPathsManagedPath[] ManagedPath {
            get {
                return this.managedPathField;
            }
            set {
                this.managedPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WebApplicationManagedPathsManagedPath {
        
        private string relativeUrlField;
        
        private bool explicitField;
        
        private bool explicitFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relativeUrl {
            get {
                return this.relativeUrlField;
            }
            set {
                this.relativeUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @explicit {
            get {
                return this.explicitField;
            }
            set {
                this.explicitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool explicitSpecified {
            get {
                return this.explicitFieldSpecified;
            }
            set {
                this.explicitFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WebApplicationSiteCollections {
        
        private SiteCollection[] siteCollectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SiteCollection")]
        public SiteCollection[] SiteCollection {
            get {
                return this.siteCollectionField;
            }
            set {
                this.siteCollectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SPSD {
        
        private SPSDConfiguration configurationField;
        
        private SPSDEnvironment environmentField;
        
        private SPSDSiteStructures siteStructuresField;
        
        private SPSDSharePoint sharePointField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDConfiguration Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDEnvironment Environment {
            get {
                return this.environmentField;
            }
            set {
                this.environmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDSiteStructures SiteStructures {
            get {
                return this.siteStructuresField;
            }
            set {
                this.siteStructuresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDSharePoint SharePoint {
            get {
                return this.sharePointField;
            }
            set {
                this.sharePointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDConfiguration {
        
        private SPSDConfigurationSettings settingsField;
        
        private SPSDConfigurationRestrictions restrictionsField;
        
        private SPSDConfigurationActions actionsField;
        
        private string idField;
        
        private string filePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDConfigurationSettings Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDConfigurationRestrictions Restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDConfigurationActions Actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDConfigurationSettings {
        
        private long deploymentRetriesField;
        
        private bool deploymentRetriesFieldSpecified;
        
        private long deploymentTimeoutField;
        
        private bool deploymentTimeoutFieldSpecified;
        
        private string runOnMultipleServersInFarmField;
        
        private string waitAfterDeploymentField;
        
        private bool displayWizardsField;
        
        private bool displayWizardsFieldSpecified;
        
        private bool createULSLogfileField;
        
        private bool createULSLogfileFieldSpecified;
        
        private string idField;
        
        private string filePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DeploymentRetries {
            get {
                return this.deploymentRetriesField;
            }
            set {
                this.deploymentRetriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeploymentRetriesSpecified {
            get {
                return this.deploymentRetriesFieldSpecified;
            }
            set {
                this.deploymentRetriesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DeploymentTimeout {
            get {
                return this.deploymentTimeoutField;
            }
            set {
                this.deploymentTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeploymentTimeoutSpecified {
            get {
                return this.deploymentTimeoutFieldSpecified;
            }
            set {
                this.deploymentTimeoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RunOnMultipleServersInFarm {
            get {
                return this.runOnMultipleServersInFarmField;
            }
            set {
                this.runOnMultipleServersInFarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WaitAfterDeployment {
            get {
                return this.waitAfterDeploymentField;
            }
            set {
                this.waitAfterDeploymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool DisplayWizards {
            get {
                return this.displayWizardsField;
            }
            set {
                this.displayWizardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayWizardsSpecified {
            get {
                return this.displayWizardsFieldSpecified;
            }
            set {
                this.displayWizardsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CreateULSLogfile {
            get {
                return this.createULSLogfileField;
            }
            set {
                this.createULSLogfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateULSLogfileSpecified {
            get {
                return this.createULSLogfileFieldSpecified;
            }
            set {
                this.createULSLogfileFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDConfigurationRestrictions {
        
        private bool allowGACDeploymentField;
        
        private bool allowGACDeploymentFieldSpecified;
        
        private bool allowCASPoliciesField;
        
        private bool allowCASPoliciesFieldSpecified;
        
        private bool allowFullTrustBinDeploymentField;
        
        private bool allowFullTrustBinDeploymentFieldSpecified;
        
        private string minimalSharePointVersionField;
        
        private string minimalSharePointLicenseField;
        
        private string idField;
        
        private string filePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool AllowGACDeployment {
            get {
                return this.allowGACDeploymentField;
            }
            set {
                this.allowGACDeploymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowGACDeploymentSpecified {
            get {
                return this.allowGACDeploymentFieldSpecified;
            }
            set {
                this.allowGACDeploymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool AllowCASPolicies {
            get {
                return this.allowCASPoliciesField;
            }
            set {
                this.allowCASPoliciesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowCASPoliciesSpecified {
            get {
                return this.allowCASPoliciesFieldSpecified;
            }
            set {
                this.allowCASPoliciesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool AllowFullTrustBinDeployment {
            get {
                return this.allowFullTrustBinDeploymentField;
            }
            set {
                this.allowFullTrustBinDeploymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowFullTrustBinDeploymentSpecified {
            get {
                return this.allowFullTrustBinDeploymentFieldSpecified;
            }
            set {
                this.allowFullTrustBinDeploymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MinimalSharePointVersion {
            get {
                return this.minimalSharePointVersionField;
            }
            set {
                this.minimalSharePointVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MinimalSharePointLicense {
            get {
                return this.minimalSharePointLicenseField;
            }
            set {
                this.minimalSharePointLicenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDConfigurationActions {
        
        private SPSDConfigurationActionsRestartService[] restartServiceField;
        
        private SPSDConfigurationActionsResetIIS resetIISField;
        
        private SPSDConfigurationActionsRecycleAppPools recycleAppPoolsField;
        
        private SPSDConfigurationActionsWarmUpUrls warmUpUrlsField;
        
        private string idField;
        
        private string filePathField;
        
        private bool afterDeployField;
        
        private bool afterDeployFieldSpecified;
        
        private bool afterRetractField;
        
        private bool afterRetractFieldSpecified;
        
        private bool afterUpdateField;
        
        private bool afterUpdateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RestartService", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDConfigurationActionsRestartService[] RestartService {
            get {
                return this.restartServiceField;
            }
            set {
                this.restartServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDConfigurationActionsResetIIS ResetIIS {
            get {
                return this.resetIISField;
            }
            set {
                this.resetIISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDConfigurationActionsRecycleAppPools RecycleAppPools {
            get {
                return this.recycleAppPoolsField;
            }
            set {
                this.recycleAppPoolsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDConfigurationActionsWarmUpUrls WarmUpUrls {
            get {
                return this.warmUpUrlsField;
            }
            set {
                this.warmUpUrlsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterDeploy {
            get {
                return this.afterDeployField;
            }
            set {
                this.afterDeployField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterDeploySpecified {
            get {
                return this.afterDeployFieldSpecified;
            }
            set {
                this.afterDeployFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterRetract {
            get {
                return this.afterRetractField;
            }
            set {
                this.afterRetractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterRetractSpecified {
            get {
                return this.afterRetractFieldSpecified;
            }
            set {
                this.afterRetractFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterUpdate {
            get {
                return this.afterUpdateField;
            }
            set {
                this.afterUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterUpdateSpecified {
            get {
                return this.afterUpdateFieldSpecified;
            }
            set {
                this.afterUpdateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDConfigurationActionsRestartService {
        
        private string nameField;
        
        private bool forceField;
        
        private bool forceFieldSpecified;
        
        private bool afterDeployField;
        
        private bool afterDeployFieldSpecified;
        
        private bool afterRetractField;
        
        private bool afterRetractFieldSpecified;
        
        private bool afterUpdateField;
        
        private bool afterUpdateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Force {
            get {
                return this.forceField;
            }
            set {
                this.forceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForceSpecified {
            get {
                return this.forceFieldSpecified;
            }
            set {
                this.forceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterDeploy {
            get {
                return this.afterDeployField;
            }
            set {
                this.afterDeployField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterDeploySpecified {
            get {
                return this.afterDeployFieldSpecified;
            }
            set {
                this.afterDeployFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterRetract {
            get {
                return this.afterRetractField;
            }
            set {
                this.afterRetractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterRetractSpecified {
            get {
                return this.afterRetractFieldSpecified;
            }
            set {
                this.afterRetractFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterUpdate {
            get {
                return this.afterUpdateField;
            }
            set {
                this.afterUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterUpdateSpecified {
            get {
                return this.afterUpdateFieldSpecified;
            }
            set {
                this.afterUpdateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDConfigurationActionsResetIIS {
        
        private bool forceField;
        
        private bool forceFieldSpecified;
        
        private bool afterDeployField;
        
        private bool afterDeployFieldSpecified;
        
        private bool afterRetractField;
        
        private bool afterRetractFieldSpecified;
        
        private bool afterUpdateField;
        
        private bool afterUpdateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Force {
            get {
                return this.forceField;
            }
            set {
                this.forceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForceSpecified {
            get {
                return this.forceFieldSpecified;
            }
            set {
                this.forceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterDeploy {
            get {
                return this.afterDeployField;
            }
            set {
                this.afterDeployField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterDeploySpecified {
            get {
                return this.afterDeployFieldSpecified;
            }
            set {
                this.afterDeployFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterRetract {
            get {
                return this.afterRetractField;
            }
            set {
                this.afterRetractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterRetractSpecified {
            get {
                return this.afterRetractFieldSpecified;
            }
            set {
                this.afterRetractFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterUpdate {
            get {
                return this.afterUpdateField;
            }
            set {
                this.afterUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterUpdateSpecified {
            get {
                return this.afterUpdateFieldSpecified;
            }
            set {
                this.afterUpdateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDConfigurationActionsRecycleAppPools {
        
        private bool allField;
        
        private bool allFieldSpecified;
        
        private bool afterDeployField;
        
        private bool afterDeployFieldSpecified;
        
        private bool afterRetractField;
        
        private bool afterRetractFieldSpecified;
        
        private bool afterUpdateField;
        
        private bool afterUpdateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool All {
            get {
                return this.allField;
            }
            set {
                this.allField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllSpecified {
            get {
                return this.allFieldSpecified;
            }
            set {
                this.allFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterDeploy {
            get {
                return this.afterDeployField;
            }
            set {
                this.afterDeployField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterDeploySpecified {
            get {
                return this.afterDeployFieldSpecified;
            }
            set {
                this.afterDeployFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterRetract {
            get {
                return this.afterRetractField;
            }
            set {
                this.afterRetractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterRetractSpecified {
            get {
                return this.afterRetractFieldSpecified;
            }
            set {
                this.afterRetractFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterUpdate {
            get {
                return this.afterUpdateField;
            }
            set {
                this.afterUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterUpdateSpecified {
            get {
                return this.afterUpdateFieldSpecified;
            }
            set {
                this.afterUpdateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDConfigurationActionsWarmUpUrls {
        
        private SPSDConfigurationActionsWarmUpUrlsWarmUp[] warmUpField;
        
        private bool allWebAppsField;
        
        private bool allWebAppsFieldSpecified;
        
        private bool allSitesField;
        
        private bool allSitesFieldSpecified;
        
        private bool afterDeployField;
        
        private bool afterDeployFieldSpecified;
        
        private bool afterUpdateField;
        
        private bool afterUpdateFieldSpecified;
        
        private bool afterRetractField;
        
        private bool afterRetractFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WarmUp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDConfigurationActionsWarmUpUrlsWarmUp[] WarmUp {
            get {
                return this.warmUpField;
            }
            set {
                this.warmUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllWebApps {
            get {
                return this.allWebAppsField;
            }
            set {
                this.allWebAppsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllWebAppsSpecified {
            get {
                return this.allWebAppsFieldSpecified;
            }
            set {
                this.allWebAppsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AllSites {
            get {
                return this.allSitesField;
            }
            set {
                this.allSitesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllSitesSpecified {
            get {
                return this.allSitesFieldSpecified;
            }
            set {
                this.allSitesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterDeploy {
            get {
                return this.afterDeployField;
            }
            set {
                this.afterDeployField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterDeploySpecified {
            get {
                return this.afterDeployFieldSpecified;
            }
            set {
                this.afterDeployFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterUpdate {
            get {
                return this.afterUpdateField;
            }
            set {
                this.afterUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterUpdateSpecified {
            get {
                return this.afterUpdateFieldSpecified;
            }
            set {
                this.afterUpdateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AfterRetract {
            get {
                return this.afterRetractField;
            }
            set {
                this.afterRetractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfterRetractSpecified {
            get {
                return this.afterRetractFieldSpecified;
            }
            set {
                this.afterRetractFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDConfigurationActionsWarmUpUrlsWarmUp {
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDEnvironment {
        
        private SPSDEnvironmentVariables variablesField;
        
        private SPSDEnvironmentPreRequisiteSolutions preRequisiteSolutionsField;
        
        private SPSDEnvironmentSolutions solutionsField;
        
        private string idField;
        
        private string filePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDEnvironmentVariables Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDEnvironmentPreRequisiteSolutions PreRequisiteSolutions {
            get {
                return this.preRequisiteSolutionsField;
            }
            set {
                this.preRequisiteSolutionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDEnvironmentSolutions Solutions {
            get {
                return this.solutionsField;
            }
            set {
                this.solutionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDEnvironmentVariables {
        
        private SPSDEnvironmentVariablesVariable[] variableField;
        
        private string idField;
        
        private string filePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Variable", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SPSDEnvironmentVariablesVariable[] Variable {
            get {
                return this.variableField;
            }
            set {
                this.variableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDEnvironmentVariablesVariable {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDEnvironmentPreRequisiteSolutions {
        
        private Solution[] solutionField;
        
        private string idField;
        
        private string filePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Solution")]
        public Solution[] Solution {
            get {
                return this.solutionField;
            }
            set {
                this.solutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDEnvironmentSolutions {
        
        private Solution[] solutionField;
        
        private string idField;
        
        private bool forceField;
        
        private bool forceFieldSpecified;
        
        private bool overwriteField;
        
        private bool overwriteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Solution")]
        public Solution[] Solution {
            get {
                return this.solutionField;
            }
            set {
                this.solutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Force {
            get {
                return this.forceField;
            }
            set {
                this.forceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForceSpecified {
            get {
                return this.forceFieldSpecified;
            }
            set {
                this.forceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OverwriteSpecified {
            get {
                return this.overwriteFieldSpecified;
            }
            set {
                this.overwriteFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDSiteStructures {
        
        private WebApplication[] webApplicationField;
        
        private string idField;
        
        private string filePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WebApplication")]
        public WebApplication[] WebApplication {
            get {
                return this.webApplicationField;
            }
            set {
                this.webApplicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDSharePoint {
        
        private SPSDSharePointVersions versionsField;
        
        private SPSDSharePointLicenses licensesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDSharePointVersions Versions {
            get {
                return this.versionsField;
            }
            set {
                this.versionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDSharePointLicenses Licenses {
            get {
                return this.licensesField;
            }
            set {
                this.licensesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDSharePointVersions {
        
        private SPSDSharePointVersionsVersion[] versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Version", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDSharePointVersionsVersion[] Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDSharePointVersionsVersion {
        
        private string numberField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDSharePointLicenses {
        
        private SPSDSharePointLicensesLicense[] licenseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("License", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SPSDSharePointLicensesLicense[] License {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SPSDSharePointLicensesLicense {
        
        private string guidField;
        
        private string typeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SPSD", typeof(SPSD))]
        [System.Xml.Serialization.XmlElementAttribute("SiteCollection", typeof(SiteCollection))]
        [System.Xml.Serialization.XmlElementAttribute("Solution", typeof(Solution))]
        [System.Xml.Serialization.XmlElementAttribute("WebApplication", typeof(WebApplication))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
